### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by stidch** [astriffe/gamecenter-clientpp#48]
Hey @astriffe 

Ich beschäftige mich (auch) grad mit dem neuen Webinterface von Swiss Volley um unsere Website anzupassen.

Gemäss meinen Informationen erhalten die Vereine mit dem erhaltenen API-Key nur beschränken Zugriff auf **games**, **rankings**, **upcomingGames** und **recentResults**.

In nachfolgendem Script habe ich einen API-Key gesehen, der anscheinend mehr Rechte hat.
https://github.com/astriffe/gamecenter-clientpp/blob/8ab7075a5df6ff4e78de939604cd345601b6b44e/src/cron/update-game-data.sh#L26

Ist dieser einer der offiziell verwendet werden kann oder ist der aus Versehen hier gelandet.

Gruss Stephan

**Comment by astriffe** [comment]
Hey @stidch 

Danke für deine Nachricht. Vorneweg: Ich habe weder mit SwissVolley noch mit Clicsoft etwas am Hut.

Ich würde natürlich niemals geheime Credentials in einem öffentlichen Repo einchecken ;-) Den erwähnten Header findest du, wenn du dir die API-Calls (spezifisch auf den `games`-Endpoint) des GameCenter auf volleyball.ch anschaust. Je nach Liga wird eine andere Authorization verwendet, beispielsweise bei der NLA dieser ominöse `clicksoftGmbhMasterApiKey`. Dieser hat praktischerweise auch gerade Zugriff auf alle anderen Verbände, bei denen das GameCenter im Einsatz ist.

Ich kann dir also nicht sagen, welche Rechte dieser API-Key hat und ob er offiziell verwendet werden kann. Um ein Versehen handelt es sich aber nicht, da der Key ja auch so schon öffentlich einsehbar ist...

Gruss, Alex

**Comment by stidch** [comment]
Hey Alex

Danke für deine Erklärung. Spannend!

Dann kann ich ja beruhigt diesen API-Key auch auf unserer Website verwenden. Mit den Standart-Rechten, welche die Vereine bekommen lässt sich ja kaum etwas machen.

![image](https://user-images.githubusercontent.com/14352675/213120936-9f90c68d-c85b-4d3a-9756-268883f2c608.png)
